# This file was generated by GoReleaser. DO NOT EDIT.
cask "nether" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "9b07644aaada8095bc248b11363b0b3ad016104bbd2565bd6231cfb6aefd9495"
      url "https://github.com/madhukraft/nether/releases/download/#{version}/nether-darwin-amd64",
        verified: "github.com/madhukraft/nether"
      binary "nether-darwin-amd64", target: "nether"
    end
    on_arm do
      sha256 "f57fc1759d11dc9a63728f1f4462184f1cf38f9c63b2705fa5b6e69f5e846a79"
      url "https://github.com/madhukraft/nether/releases/download/#{version}/nether-darwin-arm64",
        verified: "github.com/madhukraft/nether"
      binary "nether-darwin-arm64", target: "nether"
    end
  end

  on_linux do
    on_intel do
      sha256 "e893619a6556e83d1758216d0bab75371fd02cb57e716a0d805b9191eb47afd7"
      url "https://github.com/madhukraft/nether/releases/download/#{version}/nether-linux-amd64",
        verified: "github.com/madhukraft/nether"
      binary "nether-linux-amd64", target: "nether"
    end
    on_arm do
      sha256 "b292a4de54b7519c0f08394e106b957875b7cfa43ccd6983e05927fb93363fa6"
      url "https://github.com/madhukraft/nether/releases/download/#{version}/nether-linux-arm64",
        verified: "github.com/madhukraft/nether"
      binary "nether-linux-arm64", target: "nether"
    end
  end

  name "nether"
  desc "Nether - Minecraft server setup tool"
  homepage "https://github.com/madhukraft/nether"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
