# This file was generated by GoReleaser. DO NOT EDIT.
cask "nether" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "52f1510164ba736ac5c9e62c311cb5671d774dc88ef91fc20061f0eb6b459505"
      url "https://github.com/madhukraft/nether/releases/download/#{version}/nether-darwin-amd64",
        verified: "github.com/madhukraft/nether"
      binary "nether-darwin-amd64", target: "nether"
    end
    on_arm do
      sha256 "8c56ffe4adb8dd32fefb70e92a204750c5117b7c15cea66d2a9dfecc6f54e395"
      url "https://github.com/madhukraft/nether/releases/download/#{version}/nether-darwin-arm64",
        verified: "github.com/madhukraft/nether"
      binary "nether-darwin-arm64", target: "nether"
    end
  end

  on_linux do
    on_intel do
      sha256 "f7581c6418f5d1ea038fd6219305f7078704c13b0a73662bf5e5dc60d89a5388"
      url "https://github.com/madhukraft/nether/releases/download/#{version}/nether-linux-amd64",
        verified: "github.com/madhukraft/nether"
      binary "nether-linux-amd64", target: "nether"
    end
    on_arm do
      sha256 "ea526f206ea24496996e620cecd76592debbe3ea2f649decf6cec8fb5ecf5a54"
      url "https://github.com/madhukraft/nether/releases/download/#{version}/nether-linux-arm64",
        verified: "github.com/madhukraft/nether"
      binary "nether-linux-arm64", target: "nether"
    end
  end

  name "nether"
  desc "Nether - Minecraft server setup tool"
  homepage "https://github.com/madhukraft/nether"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
