# This file was generated by GoReleaser. DO NOT EDIT.
cask "nether" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "3f7b70463f8013bb460cf5c8193f9f450880a0a32f93fd7a1cbf04532f832371"
      url "https://github.com/madhukraft/nether/releases/download/#{version}/nether-darwin-amd64",
        verified: "github.com/madhukraft/nether"
      binary "nether-darwin-amd64", target: "nether"
    end
    on_arm do
      sha256 "d058209652b788116fb8f14d7ae9944b836a6a5b4a3ba21107ad0b48b9455dc9"
      url "https://github.com/madhukraft/nether/releases/download/#{version}/nether-darwin-arm64",
        verified: "github.com/madhukraft/nether"
      binary "nether-darwin-arm64", target: "nether"
    end
  end

  on_linux do
    on_intel do
      sha256 "c4d8aa6dbe0e341310aebfc9a33a024220f1b6e464d92ad60058c4ece2fbad17"
      url "https://github.com/madhukraft/nether/releases/download/#{version}/nether-linux-amd64",
        verified: "github.com/madhukraft/nether"
      binary "nether-linux-amd64", target: "nether"
    end
    on_arm do
      sha256 "56f860d3396129836aaeb5b7b551e7cb84dd19154479f6f9e47fed495a80dfce"
      url "https://github.com/madhukraft/nether/releases/download/#{version}/nether-linux-arm64",
        verified: "github.com/madhukraft/nether"
      binary "nether-linux-arm64", target: "nether"
    end
  end

  name "nether"
  desc "Nether - Minecraft server setup tool"
  homepage "https://github.com/madhukraft/nether"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

end
